### ISSUE TITLE
留言

### ISSUE THREAD

**Issue by admibrill** [imaegoo/imaegoo#1]
大佬，我最近建了一个个人空间站，但过了几天这个网站就无法访问了，但是本地运行是可以的，我想问这是为什么，是我的那个github托管的域名发现并屏蔽掉了吗，自己买一个域名可以吗，我的网址是admibrill.github.io，我在你空间站留言不了就来这了

**Comment by admibrill** [comment]
有没有可能是我网的问题？

**Comment by imaegoo** [comment]
你可以搜索如何把博客部署到Netlify，github.io在大陆地区访问受阻比较严重，绑定自己的域名之后也可以有所好转。
